# Generated by Django 4.1.7 on 2023-03-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0003_remove_reply_post_id_post_replies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="replies",
            field=models.ManyToManyField(blank=True, to="qanow.reply"),
        ),
    ]
