# Generated by Django 4.1.7 on 2023-03-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0004_alter_post_replies"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="replies",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="qanow.reply"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.TextField(
                blank=True,
                choices=[
                    ("SYLLABUS", "Syllabus"),
                    ("EXAM", "Exam"),
                    ("HW", "Homework"),
                    ("MISC", "Misc"),
                ],
                null=True,
            ),
        ),
    ]
