# Generated by Django 4.1.7 on 2023-03-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0005_reply_email_alter_post_replies_alter_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="I have a question", max_length=64),
        ),
    ]
