# Generated by Django 4.1.7 on 2023-04-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0008_remove_member_classes_class_members_class_owners_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.CharField(max_length=4000)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="embedding",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qanow.textdata",
            ),
        ),
    ]
