# Generated by Django 4.1.7 on 2023-04-14 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0009_textdata_post_embedding"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="embedding",
            new_name="textData",
        ),
    ]
