# Generated by Django 4.1.7 on 2023-04-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0010_rename_embedding_post_textdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textdata",
            name="embedding",
            field=models.JSONField(),
        ),
    ]
