# Generated by Django 4.1.7 on 2023-04-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0013_reply_parent_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="post_files/")),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="files",
            field=models.ManyToManyField(blank=True, to="qanow.file"),
        ),
        migrations.AddField(
            model_name="post",
            name="files",
            field=models.ManyToManyField(blank=True, to="qanow.file"),
        ),
        migrations.AddField(
            model_name="reply",
            name="files",
            field=models.ManyToManyField(blank=True, to="qanow.file"),
        ),
    ]
