# Generated by Django 4.1.7 on 2023-04-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0014_file_class_files_post_files_reply_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_type",
            field=models.TextField(
                choices=[
                    ("STUDENT", "Student"),
                    ("TA", "Teacher Assistant"),
                    ("INSTRUCTOR", "Instructor"),
                ],
                default="INSTRUCTOR",
            ),
        ),
    ]
