# Generated by Django 4.1.7 on 2023-04-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0015_alter_member_member_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
