# Generated by Django 4.1.7 on 2023-04-27 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0016_file_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_email", models.CharField(max_length=255)),
                ("prompt", models.CharField(max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name="reply",
            name="parent_reply",
        ),
        migrations.AddField(
            model_name="reply",
            name="nested_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_reply",
                to="qanow.parentreply",
            ),
        ),
    ]
