# Generated by Django 4.1.7 on 2023-04-27 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0017_parentreply_remove_reply_parent_reply_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="nested_reply",
            new_name="parent_reply",
        ),
    ]
