# Generated by Django 4.1.7 on 2023-04-27 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qanow", "0018_rename_nested_reply_reply_parent_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_replies",
                to="qanow.parentreply",
            ),
        ),
    ]
